name: GitHub Actions for Lint Checking and Testing
run-name: GitHub Actions run by ${{ github.actor }} 
env:
    HUSKY: 0
on: [push]
jobs:
    Lint-Checking-Testing:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20'
            - name: Prepare
              run: npm install -g pnpm && npm install
            - name: Prettier Check
              run: npm run prettier
            - name: Lint Check
              run: npm run lint
            - name: Build Project
              run: npm run build
            - name: Test Project
              run: npm run test
